name: Trigger auto deployment for c2c-node-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app2 ]
    paths:
    - '**'
    - '.github/workflows/c2c-node-2-AutoDeployTrigger-3324e5a1-a9e3-450d-ad2c-5ad6d6c200f2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.C2CNODE2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.C2CNODE2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.C2CNODE2_AZURE_SUBSCRIPTION_ID }}

      - name: Clone test repo with azure-cli-extensions whl
        uses: actions/checkout@v3
        with: 
         repository: snehapar9/test
         path: azure-cli-extensions
      
      - name: Install latest azure-cli-extensions whl
        run: az extension add -y --source '${{ github.workspace }}/azure-cli-extensions/containerapp-0.3.47-py2.py3-none-any.whl'

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@b8ae94a58470baf9b0d4c1ebd8cfeffd25931760
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.C2CNODE2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.C2CNODE2_REGISTRY_PASSWORD }}
          containerAppName: c2c-node-2
          resourceGroup: simonj-c2c-node-2
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}


